### ISSUE TITLE
Socket hang up errors

### ISSUE THREAD

**Issue by RubyKozel** [dynatrace-oss/opentelemetry-metric-js#16]
Hello,

I am using your latest version and for some reason, I encounter once in a while a "socket hang-up" error: 
https://github.com/dynatrace-oss/opentelemetry-metric-js/blob/main/src/MetricExporter.ts#L227

The problem is that when this error occurs, there's no retry of the original request - this leads to missing calls to dynatrace and eventually missing metrics that cause blank periods on the dynatrace graph.

Is there a possibility to retry the request on such an error?

**Comment by pichlermarc** [comment]
Hi @RubyKozel, thanks for reporting this!

We're currently working on a fix. 
You can track the progress in #17

**Comment by RubyKozel** [comment]
> Hi @RubyKozel, thanks for reporting this!
> 
> We're currently working on this. You can track the progress in #17

That's awesome! much appreciated!!
