### ISSUE TITLE
deprecated @opentelemetry/metrics@0.23.0

### ISSUE THREAD

**Issue by RubyKozel** [dynatrace-oss/opentelemetry-metric-js#18]
Hi,

We're getting these warnings from the library:

npm WARN deprecated @opentelemetry/metrics@0.23.0: Package renamed to @opentelemetry/sdk-metrics-base
npm WARN @dynatrace/opentelemetry-exporter-metrics@0.3.0 requires a peer of @opentelemetry/api@1.0.1 but none is installed. You must install peer dependencies yourself.

The opentelemetry/metrics is no longer exists and they changed the name
Further, can you change the peer dependencies to a higher version of opentelemetry/api ?

**Comment by dyladan** [comment]
I'll try to get to this tomorrow
