### ISSUE TITLE
OneAgent Metrics API

### ISSUE THREAD

**Issue by PatrikSteuer** [dynatrace-oss/opentelemetry-metric-js#2]
Hi,
will this instrumentation work without a token & localhost url if the OneAgent runs in pass mode? A OneAgent runs in pass mode for example on cf environments.

Are there plans to auto inject if a metric is exposed using the opentelemetry sdk and a OneAgent is in place?

Best regards
Patrik

**Comment by arminru** [comment]
Hi Patrik!
No, it will not work in PaaS mode but only if a full-stack OneAgent is installed on the host and has the metric API enabled as described here: https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/ingestion-methods/local-api/
In PaaS mode you'll have to specify a Dynatrace SaaS or Managed API endpoint and provide an auth token as documented in the readme. I'll forward the second question to PM for them to reach out to you.
Best,
Armin

**Comment by PatrikSteuer** [comment]
Thanks a lot!
