### ISSUE TITLE
Export DynatraceMetricExporter class to be used outside library

### ISSUE THREAD

**Issue by gustavokath** [dynatrace-oss/opentelemetry-metric-js#41]
**Is your feature request related to a problem? Please describe.**
Currently I have a scenario which I've built my own Reader on the top of OTLP `MetricReader` class. And in a best scenario solution I would like to use the `DynatraceMetricExporter` class which is part of this library but it unfortunately is not exported to external use.

My request id kind of simple, would be possible to make the `DynatraceMetricExporter` accessible by the library consumers? 

**Describe the solution you'd like**
I want to be able to import the `DynatraceMetricExporter` class from this library directly in my project so I could use it directly in my project without calling the `configureDynatraceMetricExport` which returns an OTLP Reader.

```ts
import { DynatraceMetricExporter } from "@dynatrace/opentelemetry-exporter-metrics"

const exporter = new DynatraceMetricExporter(options);

....

```

**Additional context**
An workaround would be to access the library files and import the file directly from `DynatraceMetricExporter.js`

```ts
import { DynatraceMetricExporter } from "@dynatrace/opentelemetry-exporter-metrics/build/src/DynatraceMetricExporter"

....
```

This works but is not clean solution, would be better if the library exported it on the `index.ts` file.

**Comment by pichlermarc** [comment]
Hi @gustavokath, thanks for reaching out. :slightly_smiling_face: 

May I ask what the use-case for using a custom `MetricReader` is (like missing features, bugs, etc.)? I'm wondering if there is something that we may be able to do upstream in the OpenTelemetry JavaScript SDK that would provide the same desired effect.

**Comment by gustavokath** [comment]
Hi @pichlermarc,
Sorry its been a  long time I kind forgot about this issue. 

Not really in my view, in my current organization we condensing the metrics collections into an internal library which is used across multiple services with different needs and using different APM tools. In the dynatrace case we use the `DynatraceMetricExporter` you developed to use some of the good enhacements it contains,  but to fit in into our own structure we require assign the exporter directly to in our own structure. 

We use a model more similar to what OpenTelemetry defines into their libraries which we provide the exporter directly to our own `MetricReader` which is also customized based on our needs.

Hope this clarifies a bit
Thanks

**Comment by pichlermarc** [comment]
Hi @gustavokath,

>  Sorry its been a long time I kind forgot about this issue.

No worries. :slightly_smiling_face: 

> Not really in my view, in my current organization we condensing the metrics collections into an internal library which is used across multiple services with different needs and using different APM tools. In the dynatrace case we use the DynatraceMetricExporter you developed to use some of the good enhacements it contains, but to fit in into our own structure we require assign the exporter directly to in our own structure. 
> 
> We use a model more similar to what OpenTelemetry defines into their libraries which we provide the exporter directly to our own MetricReader which is also customized based on our needs.

I see, so there's a custom `MetricReader` implementation that would require it?

Would using the `@opentelemetry/exporter-metrics-otlp-proto` package be an option for you? Dynatrace now supports metric ingest directly via OTLP/http-protobuf. We have recently started the process to deprecate this package, and it won't receive feature updates after the end of 2023 (see the deprecation notice we added to https://github.com/dynatrace-oss/opentelemetry-metric-js#dynatrace-opentelemetry-metrics-exporter-for-javascript), so switching to OTLP would be the preferred option.

**Comment by gustavokath** [comment]
Hi @pichlermarc

> Would using the `@opentelemetry/exporter-metrics-otlp-proto` package be an option for you? Dynatrace now supports metric ingest directly via OTLP/http-protobuf. We have recently started the process to deprecate this package, and it won't receive feature updates after the end of 2023 (see the deprecation notice we added to https://github.com/dynatrace-oss/opentelemetry-metric-js#dynatrace-opentelemetry-metrics-exporter-for-javascript), so switching to OTLP would be the preferred option.

I noticed this deprecation notice this week, this sound great for my scenario as everything will be OTLP. I would only have a few questions and concerns, it would be great if have some more details.

1. Currently Histograms metrics are not supported by Dynatrace [according](https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/getting-started/metrics/ingest/migration-guide-otlp-exporter#in-applications-additional-features), is there any plans and timeline to start supporting this? This is main reason why I'm using the lib is the conversion it makes to Dynatrace Gauge for the proprietary API.
2. On this lib there was the possibility to send the metrics to the OneAgent which would send transmit them to the server, avoiding extra costs. Is there the same possibility with the OTLP exporters? Is the OneAgent being enhanced to understand OTLP APIs?

Thank you

**Comment by pirgeo** [comment]
Hi @gustavokath,

I think both questions would be good candidates for the Dynatrace community forum: https://community.dynatrace.com/. I know that we are working on many things in these areas, but I don’t know exact timelines or details. Folks on the forum might have more insights!

Thanks a lot

**Comment by arminru** [comment]
Hi @gustavokath! Please note that the deprecation of this exporter which we announced in July 2023 has come into effect now and we will not provide any new features or adaptions. You can find the reasoning and alternatives described here: https://github.com/dynatrace-oss/opentelemetry-metric-js#dynatrace-opentelemetry-metrics-exporter-for-javascript
